name: Publish Dumpify

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
   
    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src -c Release --no-restore
      
    - name: Create Nuget Package
      run: dotnet pack -c Release /p:Version=${{github.event.release.tag_name}} /p:PackageReleaseNotes="See https://github.com/MoaidHathot/Dumpify/releases/tag/${{github.event.release.tag_name}}" ./src/Dumpify
    
    - name: Archive Nuget Package for Dumpify
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: "./src/Dumpify/bin/Release/Dumpify.${{github.event.release.tag_name}}.nupkg"

    - name: Publish Nuget Package
      run: dotnet nuget push ./src/**/*.nupkg --source https://nuget.pkg.github.com/hermanussen/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
